### ISSUE TITLE
Rule and custom Attribute on lang file

### ISSUE THREAD

**Issue by kaxias** [somnambulist-tech/validation#29]
Normally we do like this.
```php
<?php

return [
    'rule.required' => 'The :attribute field is required.',
];
```
would be nice if we could do something like this.

```php
<?php

return [
    'rule' => [
         'required' => 'The :attribute field is required.',
    ],

    'custom-attribute' => [
        'custom_field' => 'custom field',
    ],
];
```

**Comment by dave-redfern** [comment]
@kaxias you mean allowing nested arrays for defining translation messages?

Personally I am not a huge fan of heavily nested arrays for things like these. Do you have specific reasons?

**Comment by messikiller** [comment]
It is possible that the  key of array maybe contains "." flag already. it would be better if the dot flag can be specified by the user...

**Comment by dave-redfern** [comment]
Closing due to lack of feedback. If there is an actual use case for changing the translation message format, I am more than happy to discuss it.

As an alternative: custom translations for custom attributes can be added using the dot format (see the docs). Copy the existing files and add whatever others you desire. If you really want nested arrays, then you can add a pre-processor that concats the array keys together before adding the messages to the Factory.
